"""Profile-driven correlation engine for static analysis findings.

This module transforms normalized static `Signal` objects into a correlation
model that includes procedure hypotheses, relationship edges, risk score, and
priority. Scoring is bounded to `[0, 100]` and modulated by deployment context
and repeated evidence counts.

Interpretation limits:
- Correlation output is a prioritization heuristic, not proof of compromise.
- Procedure chains represent rule satisfaction, not observed execution traces.
- Unknown/invalid context values are normalized to conservative defaults.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from worker_static.domain.constants import SEVERITY_HIGH, SEVERITY_LOW, SEVERITY_MEDIUM
from worker_static.domain.models import Signal

DEFAULT_PROFILE = "LINUX_SERVER"
DEFAULT_DEPLOYMENT_CONTEXT = {
    "exposure": "INTERNAL",
    "privilegeLevel": "USER",
    "dataSensitivity": "MEDIUM",
}


def build_correlation(
    signals: list[Signal],
    environment_profile: str = DEFAULT_PROFILE,
    deployment_context: dict | None = None,
    observed_runs: int = 1,
) -> dict:
    """Correlate static findings using profile-driven rules and weights.

    Args:
        signals: Normalized signal list generated by static analyzers.
        environment_profile: Environment key used to resolve a JSON correlation
            profile. Unsupported values fall back to `LINUX_SERVER`.
        deployment_context: Optional runtime exposure assumptions. Supported
            keys are `exposure`, `privilegeLevel`, and `dataSensitivity`.
        observed_runs: Number of confirmations available for the same artifact.
            Values below 1 are normalized to 1.

    Returns:
        dict: Correlation payload with profile metadata, risk score/priority,
        procedure matches, relationships, exploitability factors, and top
        rationale entries.

    Raises:
        ValueError: If `observed_runs` cannot be converted to integer.

    Side Effects:
        Reads a correlation profile JSON file from
        `analysis/correlation_profiles` (cached after first load).
    """
    profile = _load_profile(environment_profile)
    context = _normalize_deployment_context(deployment_context)
    safe_runs = max(1, int(observed_runs))
    procedures: list[dict] = []
    relationships: list[dict] = []
    chain_score_bonus = 0

    for rule in profile["procedureRules"]:
        matched_signals = [
            signal
            for signal in signals
            if signal.kind in set(rule["signalKinds"])
        ]
        if not matched_signals:
            continue

        score = min(
            100,
            int(rule["baseScore"])
            + (len(matched_signals) - 1) * int(profile["procedureScoreStep"]),
        )
        procedure = {
            "procedureId": rule["id"],
            "title": rule["title"],
            "score": score,
            "severity": _severity_from_score(score, profile),
            "signalIds": [signal.id for signal in matched_signals],
            "rationale": rule["rationale"],
        }
        procedures.append(procedure)
        relationships.extend(
            {
                "fromSignalId": signal.id,
                "toProcedureId": rule["id"],
                "type": rule["signalRelationType"],
                "reason": signal.title,
            }
            for signal in matched_signals
        )

    procedure_ids = {procedure["procedureId"] for procedure in procedures}
    for chain_rule in profile["chainRules"]:
        required = set(chain_rule["requires"])
        if not required.issubset(procedure_ids):
            continue
        chain_score_bonus += int(
            chain_rule.get(
                "scoreBonus",
                profile["scoreBonuses"].get("chainRule", 0),
            )
        )
        relationships.append(
            {
                "fromProcedureId": chain_rule["fromProcedureId"],
                "toProcedureId": chain_rule["toProcedureId"],
                "type": chain_rule["type"],
                "reason": chain_rule["reason"],
            }
        )

    risk_score = _resolve_risk_score(
        signals,
        procedures,
        profile,
        context,
        safe_runs,
        chain_score_bonus,
    )
    exploitability = _build_exploitability(
        procedures,
        relationships,
        context,
        safe_runs,
        risk_score,
    )
    return {
        "version": profile["version"],
        "environmentProfile": profile["environmentProfile"],
        "deploymentContext": context,
        "riskScore": risk_score,
        "priority": _priority_from_score(risk_score, profile),
        "procedures": sorted(procedures, key=lambda row: row["score"], reverse=True),
        "relationships": relationships,
        "executionEvidence": {
            "observedRuns": safe_runs,
            "consistency": "HIGH" if safe_runs >= 3 else "MEDIUM" if safe_runs == 2 else "LOW",
            "note": "Static evidence can be reinforced by repeated dynamic confirmations.",
        },
        "exploitability": exploitability,
        "topReasons": _top_reasons(procedures),
    }


def resolve_risk_level_from_score(
    risk_score: int,
    environment_profile: str = DEFAULT_PROFILE,
) -> str:
    """Map a numeric score to LOW/MEDIUM/HIGH using profile thresholds.

    Args:
        risk_score: Aggregate risk score expected in the `[0, 100]` range.
        environment_profile: Environment key used to pick threshold values.

    Returns:
        str: Severity label (`LOW`, `MEDIUM`, or `HIGH`) according to the resolved
        profile thresholds.

    Side Effects:
        May trigger a profile JSON read on first access for a profile.
    """
    profile = _load_profile(environment_profile)
    return _severity_from_score(risk_score, profile)


def _resolve_risk_score(
    signals: list[Signal],
    procedures: list[dict],
    profile: dict,
    deployment_context: dict,
    observed_runs: int,
    chain_score_bonus: int,
) -> int:
    severity_weights = profile["severityWeights"]
    score = sum(int(severity_weights.get(signal.severity, 0)) for signal in signals)
    if procedures:
        max_divisor = int(profile["scoreBonuses"]["maxProcedureDivisor"])
        score += max(procedure["score"] for procedure in procedures) // max_divisor
        critical_threshold = int(profile["scoreBonuses"].get("criticalProcedureThreshold", 90))
        if any(int(procedure["score"]) >= critical_threshold for procedure in procedures):
            score += int(profile["scoreBonuses"].get("criticalProcedure", 0))
    if len(procedures) >= 2:
        score += int(profile["scoreBonuses"]["multiProcedure"])
    score += _deployment_bonus(deployment_context)
    score += min(6, (observed_runs - 1) * 2)
    score += int(chain_score_bonus)
    return max(0, min(100, score))


def _deployment_bonus(deployment_context: dict) -> int:
    exposure_bonus = {
        "INTERNET": 8,
        "EXTERNAL": 5,
        "INTERNAL": 2,
        "ISOLATED": 0,
    }
    privilege_bonus = {
        "ROOT": 8,
        "PRIVILEGED": 5,
        "USER": 2,
    }
    sensitivity_bonus = {
        "HIGH": 6,
        "MEDIUM": 3,
        "LOW": 1,
    }
    return (
        exposure_bonus.get(deployment_context["exposure"], 2)
        + privilege_bonus.get(deployment_context["privilegeLevel"], 2)
        + sensitivity_bonus.get(deployment_context["dataSensitivity"], 3)
    )


def _build_exploitability(
    procedures: list[dict],
    relationships: list[dict],
    deployment_context: dict,
    observed_runs: int,
    risk_score: int,
) -> dict:
    top_procedure = max((int(item["score"]) for item in procedures), default=0)
    chain_count = len([item for item in relationships if "fromProcedureId" in item])

    reachability = min(
        100,
        30
        + (15 if deployment_context["exposure"] in {"INTERNET", "EXTERNAL"} else 6)
        + min(20, top_procedure // 4),
    )
    impact = min(
        100,
        30
        + (18 if deployment_context["privilegeLevel"] in {"ROOT", "PRIVILEGED"} else 8)
        + (12 if deployment_context["dataSensitivity"] == "HIGH" else 6),
    )
    confidence = min(
        100,
        35 + min(25, observed_runs * 6) + min(20, chain_count * 5),
    )
    exploitability_score = max(
        0,
        min(100, int((reachability + impact + confidence + risk_score) / 4)),
    )

    reasons = [
        (
            f"Exposure={deployment_context['exposure']} and "
            f"privilege={deployment_context['privilegeLevel']} "
            "raise practical impact."
        ),
        f"Observed runs={observed_runs} and procedure chains={chain_count} improve confidence.",
    ]

    return {
        "score": exploitability_score,
        "reachability": reachability,
        "impact": impact,
        "confidence": confidence,
        "reasons": reasons,
    }


def _severity_from_score(score: int, profile: dict) -> str:
    high = int(profile["riskThresholds"]["high"])
    medium = int(profile["riskThresholds"]["medium"])
    if score >= high:
        return SEVERITY_HIGH
    if score >= medium:
        return SEVERITY_MEDIUM
    return SEVERITY_LOW


def _priority_from_score(score: int, profile: dict) -> str:
    p1 = int(profile["priorityThresholds"]["p1"])
    p2 = int(profile["priorityThresholds"]["p2"])
    if score >= p1:
        return "P1"
    if score >= p2:
        return "P2"
    return "P3"


def _top_reasons(procedures: list[dict]) -> list[str]:
    ordered = sorted(procedures, key=lambda row: row["score"], reverse=True)
    return [
        f"{item['title']} ({item['severity']}) - {item['rationale']}"
        for item in ordered[:3]
    ]


@lru_cache(maxsize=8)
def _load_profile(environment_profile: str) -> dict:
    normalized = environment_profile.strip().upper() if environment_profile else DEFAULT_PROFILE
    profile_path = _profile_path(normalized)
    if not profile_path.exists():
        profile_path = _profile_path(DEFAULT_PROFILE)
    return json.loads(profile_path.read_text(encoding="utf-8"))


def _profile_path(environment_profile: str) -> Path:
    profile_dir = Path(__file__).with_name("correlation_profiles")
    file_name = {
        "LINUX_SERVER": "linux_server_v1.json",
        "CONTAINER_SERVICE": "container_service_v1.json",
    }.get(environment_profile, "linux_server_v1.json")
    return profile_dir / file_name


def _normalize_deployment_context(deployment_context: dict | None) -> dict:
    raw = dict(DEFAULT_DEPLOYMENT_CONTEXT)
    if deployment_context:
        raw.update({k: str(v).strip().upper() for k, v in deployment_context.items() if v})

    exposure = raw.get("exposure", "INTERNAL")
    privilege = raw.get("privilegeLevel", "USER")
    sensitivity = raw.get("dataSensitivity", "MEDIUM")

    if exposure not in {"INTERNET", "EXTERNAL", "INTERNAL", "ISOLATED"}:
        exposure = "INTERNAL"
    if privilege not in {"ROOT", "PRIVILEGED", "USER"}:
        privilege = "USER"
    if sensitivity not in {"HIGH", "MEDIUM", "LOW"}:
        sensitivity = "MEDIUM"

    return {
        "exposure": exposure,
        "privilegeLevel": privilege,
        "dataSensitivity": sensitivity,
    }
