package com.ppaob.backend.domain.model;

import java.time.Instant;
import java.util.UUID;

/**
 * Metadata of an artifact generated by an analysis run.
 *
 * <p>Artifacts are derived outputs (reports, transformed files, auxiliary data) that
 * remain linked to their originating analysis through {@code analysisId}. Storage
 * location is external and referenced by object metadata fields.
 *
 * @param artifactId unique artifact identifier.
 * @param analysisId identifier of the analysis that produced the artifact.
 * @param binaryOriginalName source binary name snapshot kept for traceability.
 * @param type artifact kind/category used by consumers.
 * @param createdAt artifact creation timestamp.
 * @param objectId storage object identifier in the persistence layer.
 * @param bucket storage bucket/container where the artifact is stored.
 * @param objectKey object path/key inside the bucket.
 * @param sizeBytes artifact size in bytes.
 */
public record ArtifactRecord(
        UUID artifactId,
        UUID analysisId,
        String binaryOriginalName,
        String type,
        Instant createdAt,
        UUID objectId,
        String bucket,
        String objectKey,
        long sizeBytes
) {
}
