"""Profile-driven correlation and scoring for dynamic telemetry.

The correlation flow maps normalized runtime/policy evidence to profile rules,
derives procedure-level findings, links eligible procedure chains, and computes
bounded risk/exploitability scores for triage prioritization.

Interpretation limits:
- Inputs are observation-only signals from instrumented execution.
- Scores are heuristic and profile-dependent, not proof of exploitability.
- Unknown profile/context values are normalized to conservative defaults.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

DEFAULT_PROFILE = "LINUX_SERVER"
DEFAULT_DEPLOYMENT_CONTEXT = {
    "exposure": "INTERNAL",
    "privilegeLevel": "USER",
    "dataSensitivity": "MEDIUM",
}


def build_correlation(
    runtime: dict,
    policy: dict,
    top_syscalls: list[dict],
    signals: list[dict],
    environment_profile: str = DEFAULT_PROFILE,
    deployment_context: dict | None = None,
    observed_runs: int = 1,
) -> dict:
    """Build correlation output from normalized dynamic execution artifacts.

    Args:
        runtime: Runtime block from the agent payload. Expected keys include
            `timedOut`, `durationMs`, and optionally termination metadata.
        policy: Policy block from the agent payload. Expected keys include
            `deniedCount` and policy identity fields.
        top_syscalls: Ranked syscall-frequency list where each row may include
            `name`; only normalized syscall names are used for matching.
        signals: Normalized findings generated by the dynamic runner.
        environment_profile: Logical correlation profile identifier.
        deployment_context: Optional environment assumptions (`exposure`,
            `privilegeLevel`, `dataSensitivity`) used by scoring bonuses.
        observed_runs: Number of independent observations included in this
            assessment; values lower than 1 are clamped to 1.

    Returns:
        dict: Correlation payload with procedures, relationships, bounded risk
        score, execution evidence, exploitability decomposition, and top
        reasons.

    Side Effects:
        Reads profile JSON from `analysis/correlation_profiles/` through a
        cached profile loader.
    """
    profile = _load_profile(environment_profile)
    context = _normalize_deployment_context(deployment_context)
    safe_runs = max(1, int(observed_runs))
    syscall_names = {
        str(entry.get("name", "")).strip().lower()
        for entry in top_syscalls
        if str(entry.get("name", "")).strip()
    }

    procedures: list[dict] = []
    relationships: list[dict] = []
    chain_score_bonus = 0

    for rule in profile["procedureRules"]:
        evidence = _rule_evidence(rule, syscall_names, runtime, policy)
        if not evidence:
            continue
        score = min(
            100,
            int(rule["baseScore"]) + (len(evidence) - 1) * int(profile["procedureScoreStep"]),
        )
        procedures.append(
            {
                "procedureId": rule["id"],
                "title": rule["title"],
                "score": score,
                "severity": _severity_from_score(score, profile),
                "evidence": evidence,
                "rationale": rule["rationale"],
            }
        )

    procedure_ids = {procedure["procedureId"] for procedure in procedures}
    for chain_rule in profile["chainRules"]:
        required = set(chain_rule["requires"])
        if not required.issubset(procedure_ids):
            continue
        chain_score_bonus += int(
            chain_rule.get(
                "scoreBonus",
                profile["scoreBonuses"].get("chainRule", 0),
            )
        )
        relationships.append(
            {
                "fromProcedureId": chain_rule["fromProcedureId"],
                "toProcedureId": chain_rule["toProcedureId"],
                "type": chain_rule["type"],
                "reason": chain_rule["reason"],
            }
        )

    risk_score = _resolve_risk_score(
        runtime,
        policy,
        procedures,
        signals,
        profile,
        context,
        safe_runs,
        chain_score_bonus,
    )
    exploitability = _build_exploitability(
        runtime,
        procedures,
        relationships,
        context,
        safe_runs,
        risk_score,
    )
    return {
        "version": profile["version"],
        "environmentProfile": profile["environmentProfile"],
        "deploymentContext": context,
        "riskScore": risk_score,
        "priority": _priority_from_score(risk_score, profile),
        "procedures": sorted(procedures, key=lambda row: row["score"], reverse=True),
        "relationships": relationships,
        "executionEvidence": {
            "observedRuns": safe_runs,
            "timedOut": runtime.get("timedOut") is True,
            "durationMs": int(runtime.get("durationMs", 0)),
            "deniedSyscalls": int(policy.get("deniedCount", 0)),
        },
        "exploitability": exploitability,
        "topReasons": _top_reasons(procedures),
    }


def resolve_risk_level_from_score(risk_score: int, environment_profile: str = DEFAULT_PROFILE) -> str:
    """Map a numeric risk score to a profile-specific severity bucket.

    Args:
        risk_score: Bounded score expected in the [0, 100] range.
        environment_profile: Logical profile identifier used to resolve
            threshold configuration.

    Returns:
        str: `LOW`, `MEDIUM`, or `HIGH` according to profile thresholds.

    Side Effects:
        Reads profile JSON via the cached loader when not already cached.
    """
    profile = _load_profile(environment_profile)
    return _severity_from_score(risk_score, profile)


def _rule_evidence(rule: dict, syscall_names: set[str], runtime: dict, policy: dict) -> list[str]:
    rule_type = rule["type"]
    if rule_type == "syscall_any":
        matched = sorted(syscall_names.intersection({name.lower() for name in rule["syscalls"]}))
        minimum = int(rule.get("minMatches", 1))
        return matched if len(matched) >= minimum else []
    if rule_type == "policy_denied":
        denied_count = int(policy.get("deniedCount", 0))
        minimum = int(rule.get("minDeniedCount", 1))
        if denied_count >= minimum:
            return [f"denied:{denied_count}"]
        return []
    if rule_type == "runtime_timeout":
        if runtime.get("timedOut") is True:
            return [f"durationMs:{int(runtime.get('durationMs', 0))}"]
        return []
    return []


def _resolve_risk_score(
    runtime: dict,
    policy: dict,
    procedures: list[dict],
    signals: list[dict],
    profile: dict,
    deployment_context: dict,
    observed_runs: int,
    chain_score_bonus: int,
) -> int:
    score = int(profile["scoreBase"])
    score += len(signals) * int(profile["signalWeight"])

    if runtime.get("timedOut") is True:
        score += int(profile["scoreBonuses"]["timedOut"])
    if int(policy.get("deniedCount", 0)) > 0:
        score += int(profile["scoreBonuses"]["policyDenied"])
    if procedures:
        divisor = int(profile["scoreBonuses"]["maxProcedureDivisor"])
        score += max(procedure["score"] for procedure in procedures) // divisor
        critical_threshold = int(profile["scoreBonuses"].get("criticalProcedureThreshold", 90))
        if any(int(procedure["score"]) >= critical_threshold for procedure in procedures):
            score += int(profile["scoreBonuses"].get("criticalProcedure", 0))
    if len(procedures) >= 3:
        score += int(profile["scoreBonuses"]["multiProcedure"])
    score += _deployment_bonus(deployment_context)
    score += min(8, (observed_runs - 1) * 3)
    if runtime.get("timedOut") is True and int(policy.get("deniedCount", 0)) > 0:
        score += int(profile["scoreBonuses"].get("timedOutDeniedCombo", 6))
    score += int(chain_score_bonus)

    return max(0, min(100, score))


def _deployment_bonus(deployment_context: dict) -> int:
    exposure_bonus = {
        "INTERNET": 8,
        "EXTERNAL": 5,
        "INTERNAL": 2,
        "ISOLATED": 0,
    }
    privilege_bonus = {
        "ROOT": 8,
        "PRIVILEGED": 5,
        "USER": 2,
    }
    sensitivity_bonus = {
        "HIGH": 6,
        "MEDIUM": 3,
        "LOW": 1,
    }
    return (
        exposure_bonus.get(deployment_context["exposure"], 2)
        + privilege_bonus.get(deployment_context["privilegeLevel"], 2)
        + sensitivity_bonus.get(deployment_context["dataSensitivity"], 3)
    )


def _build_exploitability(
    runtime: dict,
    procedures: list[dict],
    relationships: list[dict],
    deployment_context: dict,
    observed_runs: int,
    risk_score: int,
) -> dict:
    top_procedure = max((int(item["score"]) for item in procedures), default=0)
    chain_count = len([item for item in relationships if "fromProcedureId" in item])
    timeout_bonus = 12 if runtime.get("timedOut") is True else 0

    reachability = min(
        100,
        34
        + (15 if deployment_context["exposure"] in {"INTERNET", "EXTERNAL"} else 6)
        + min(18, top_procedure // 5),
    )
    impact = min(
        100,
        34
        + (18 if deployment_context["privilegeLevel"] in {"ROOT", "PRIVILEGED"} else 8)
        + (12 if deployment_context["dataSensitivity"] == "HIGH" else 6)
        + timeout_bonus,
    )
    confidence = min(100, 40 + min(25, observed_runs * 6) + min(20, chain_count * 5))
    exploitability_score = max(0, min(100, int((reachability + impact + confidence + risk_score) / 4)))

    reasons = [
        f"Exposure={deployment_context['exposure']} and privilege={deployment_context['privilegeLevel']} increase potential blast radius.",
        f"Observed runs={observed_runs} with runtime chains={chain_count} increase confidence in reproducibility.",
    ]

    return {
        "score": exploitability_score,
        "reachability": reachability,
        "impact": impact,
        "confidence": confidence,
        "reasons": reasons,
    }


def _severity_from_score(score: int, profile: dict) -> str:
    high = int(profile["riskThresholds"]["high"])
    medium = int(profile["riskThresholds"]["medium"])
    if score >= high:
        return "HIGH"
    if score >= medium:
        return "MEDIUM"
    return "LOW"


def _priority_from_score(score: int, profile: dict) -> str:
    p1 = int(profile["priorityThresholds"]["p1"])
    p2 = int(profile["priorityThresholds"]["p2"])
    if score >= p1:
        return "P1"
    if score >= p2:
        return "P2"
    return "P3"


def _top_reasons(procedures: list[dict]) -> list[str]:
    ordered = sorted(procedures, key=lambda row: row["score"], reverse=True)
    return [
        f"{item['title']} ({item['severity']}) - {item['rationale']}"
        for item in ordered[:3]
    ]


@lru_cache(maxsize=8)
def _load_profile(environment_profile: str) -> dict:
    normalized = environment_profile.strip().upper() if environment_profile else DEFAULT_PROFILE
    profile_path = _profile_path(normalized)
    if not profile_path.exists():
        profile_path = _profile_path(DEFAULT_PROFILE)
    return json.loads(profile_path.read_text(encoding="utf-8"))


def _profile_path(environment_profile: str) -> Path:
    profile_dir = Path(__file__).with_name("correlation_profiles")
    file_name = {
        "LINUX_SERVER": "linux_server_v1.json",
        "CONTAINER_SERVICE": "container_service_v1.json",
    }.get(environment_profile, "linux_server_v1.json")
    return profile_dir / file_name


def _normalize_deployment_context(deployment_context: dict | None) -> dict:
    raw = dict(DEFAULT_DEPLOYMENT_CONTEXT)
    if deployment_context:
        raw.update({k: str(v).strip().upper() for k, v in deployment_context.items() if v})

    exposure = raw.get("exposure", "INTERNAL")
    privilege = raw.get("privilegeLevel", "USER")
    sensitivity = raw.get("dataSensitivity", "MEDIUM")

    if exposure not in {"INTERNET", "EXTERNAL", "INTERNAL", "ISOLATED"}:
        exposure = "INTERNAL"
    if privilege not in {"ROOT", "PRIVILEGED", "USER"}:
        privilege = "USER"
    if sensitivity not in {"HIGH", "MEDIUM", "LOW"}:
        sensitivity = "MEDIUM"

    return {
        "exposure": exposure,
        "privilegeLevel": privilege,
        "dataSensitivity": sensitivity,
    }
